name: evently
description: "A simple and modern Flutter app for event management."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸ§© Core Packages
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  animated_toggle_switch: ^0.8.5
  flutter_localization: ^0.3.3
  smooth_page_indicator: ^1.2.1
  http: ^1.1.0
  intl: ^0.20.2
  google_generative_ai: ^0.4.7

  # ðŸ”¥ Firebase (ÙƒÙ„Ù‡Ù… Ù…ØªÙˆØ§ÙÙ‚ÙŠÙ† Ø³ÙˆØ§)
  firebase_core: ^3.10.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.0.2

  # ðŸ” Google Sign-In
  google_sign_in: ^6.2.1
  buttons_tabbar: ^1.3.15
  fluttertoast: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterBold.ttf
          weight: 700

flutter_intl:
  enabled: true
